# Generated by Django 3.2.20 on 2023-09-13 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter username', max_length=100)),
                ('password', models.CharField(help_text='Enter password', max_length=100)),
                ('email', models.EmailField(help_text='Enter email', max_length=254)),
                ('first_name', models.CharField(help_text='Enter first name', max_length=50)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a song name', max_length=200)),
                ('image', models.ImageField(height_field=100, upload_to='cover_image', width_field=100)),
                ('content', models.FileField(upload_to='songs')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a playlist name', max_length=200)),
                ('image', models.ImageField(height_field=100, upload_to='cover_image', width_field=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
