# Generated by Django 3.2.20 on 2023-09-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.BooleanField(default=False, help_text='Check this box to make the song public'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Enter a song tags', max_length=20),
        ),
    ]
