# Generated by Django 4.2.5 on 2023-09-21 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_playlistsong_playlist_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='songs',
        ),
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.ManyToManyField(through='catalog.UserSong', to='catalog.song'),
        ),
    ]
