# Generated by Django 4.2.5 on 2023-09-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_user_history_listenlater'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenlater',
            name='listen_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='history',
            field=models.ManyToManyField(through='catalog.UserSong', to='catalog.song'),
        ),
    ]
