# Generated by Django 3.2.20 on 2023-09-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listen_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
