# Generated by Django 3.2.20 on 2023-09-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_song_listen_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='cover_image'),
        ),
    ]
