# Generated by Django 3.2.20 on 2023-09-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20230924_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='', help_text='Enter a playlist name', max_length=200),
        ),
    ]
