# Generated by Django 3.2.20 on 2023-09-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(default='', help_text='Enter a song name', max_length=200),
        ),
    ]
