# Generated by Django 3.2.20 on 2023-10-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_song_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.song')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.tag')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(through='catalog.SongTag', to='catalog.Tag'),
        ),
    ]
