# Generated by Django 4.2.5 on 2023-09-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_listenlater_listen_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listenlater',
            old_name='listen_id',
            new_name='listen',
        ),
    ]
