# Generated by Django 4.2.5 on 2023-09-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(upload_to='cover_image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='content',
            field=models.FileField(upload_to='media/songs'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='media/cover_image'),
        ),
    ]
