# Generated by Django 4.2.5 on 2023-09-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_playlist_image_alter_song_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='content',
            field=models.FileField(upload_to='songs'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='cover_image'),
        ),
    ]
