# Generated by Django 4.2.5 on 2023-09-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_commentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentForm',
            new_name='Comment',
        ),
    ]
