# Generated by Django 4.2.5 on 2023-10-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_song_like_count_songtag_song_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersong',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
